### ISSUE TITLE
Code details

### ISSUE THREAD

**Issue by ypmacc** [nesteant/icpc-trainer#10]
[Each code](https://prnt.sc/h2s96e) should have the following details from the ICPC2 translation table as per [spec 5.2](https://docs.google.com/document/d/1qaXZ4l4NqUfE2HEElig17agOxJU-vBvrG4fb8501MvQ/edit):
*Обраний код + назва ІСРС (dropdown list)
*Код + назва MKX-10 (non-editable text field, asking whether it can be provided as those are missing)
*Включення  (non-editable text area)
*Виключення  (non-editable text  area)
*Критерії  (non-editable text area)
*Розглянути  (non-editable text area)
*Примітки  (EDITABLE text area, the text is local for the given sub-encounter, not global).

IMO it's better to have it in one column, in the rows just like [here](https://prnt.sc/h2sfxq). What do you think?

**Comment by nesteant** [comment]
Please check with the current implementation and add additional comments if any

**Comment by ypmacc** [comment]
[Existing](https://prnt.sc/h3k5y5) sub-encounter view should also be fixed.
