### ISSUE TITLE
Fix create sub-encounter pop-up

### ISSUE THREAD

**Issue by ypmacc** [nesteant/icpc-trainer#15]
1. The [calendar](https://prnt.sc/hdayue) should be in european format, i.e. the week should start from Monday.
2. Please change "Причина" to "Причина звернення" here and all over the app.

**Comment by nesteant** [comment]
moved 3d point to the separate issue

**Comment by YuraBorsch** [comment]
3. Please make the current data to be prefilled in the date field.

**Comment by ypmacc** [comment]
3. The date field should be prepopulated with the current date.

**Comment by ypmacc** [comment]
1. Is it possible to translate the calendar/date picker widget to Ukrainian?
2. and 3. - ok.

**Comment by ypmacc** [comment]
Fixed.
