### ISSUE TITLE
Episode naming

### ISSUE THREAD

**Issue by ypmacc** [nesteant/icpc-trainer#3]
Episode name should consist of diagnosis + arbitrary string entered by MP.

**Comment by nesteant** [comment]
As was discussed it is entered manually. Do you want the name to be prefixed automatically with the diagnosis?

**Comment by ypmacc** [comment]
For the prefix it's better to have a dropdown list with the automatic selection of the diagnosis as per diagnosis tab value.

**Comment by nesteant** [comment]
Where should it be added? 

Adding of new subvisit with creation of new episode?
Adding of new subvisit with using existing episode?
Modifying episode?

**Comment by ypmacc** [comment]
1 and 3. We need to have the episode naming functionality when creating sub-encounter and adding it new episode (1), and renaming episode functionality in eposode view/popup (3).

**Comment by nesteant** [comment]
fixed

**Comment by ypmacc** [comment]
We are almost there. The first part should be a diagnosis code and diagnosis name. Just like in subencounter. The second part should be manually entered by MP, should be empty by default and most probably will be a date (just to differ separate unrelated episodes with the same diagnosis).

**Comment by nesteant** [comment]
please check

**Comment by ypmacc** [comment]
https://marvelapp.com/2j6id9a/screen/33766573

**Comment by nesteant** [comment]
added text and naming
