### ISSUE TITLE
Selected reason/diagnosis/intervention

### ISSUE THREAD

**Issue by ypmacc** [nesteant/icpc-trainer#4]
When managing sub-encounters and moving between tabs of reason/diagnosis/intervention, the selected values should be visible from any tab. As per [specification](https://docs.google.com/document/d/1qaXZ4l4NqUfE2HEElig17agOxJU-vBvrG4fb8501MvQ/edit): "При переході між вкладками (причина звернення – діагноз – дії) повинні бути видимими вже визначені коди інших вкладок."

**Comment by nesteant** [comment]
As was discussed codes are copied to the action tab and can be managed there. What should be exactly done? Should they be only shown, copied and be editable or should be shared and editable>

**Comment by ypmacc** [comment]
The selected codes should be visible from any tab. Let's say you entered a reason and clicked on the "next" button. The diagnosis tab becomes active, but from this tab you should see what reason was selected (without moving between tabs). Same for all tabs.

**Comment by nesteant** [comment]
As for now action tab copies all these values - should it also show duplicates of what has been copied?

**Comment by ypmacc** [comment]
It should be on the tab itself, just under the "Причина" label.

**Comment by nesteant** [comment]
Please check

**Comment by ypmacc** [comment]
Ok, it's something but not what's needed because you can't tell what code is for what. The selected code (and corresponding text) should be one the tab (tab name), as I mentioned above, not the tab content.

**Comment by nesteant** [comment]
Actually adding it to the tab name will cause to be huge as for reasons we can select several codes

**Comment by ypmacc** [comment]
Agreed, but I don't see another way to make it clear and visible. An alternative could by writing the selected values in the text area, but under the corresponding tabs like [this](https://marvelapp.com/2j6id9a/screen/33776376).

**Comment by nesteant** [comment]
mmm. Could it be tooltips, collapsible areas etc?

**Comment by ypmacc** [comment]
It should be visible while navigating the tabs. When on diagnosis tab, the doctor should clearly see the reasons. Same for interventions. It should be all clear so nothing is missed by the doctor when creating a sub encounter.
