### ISSUE TITLE
Sub-encounter - episode association

### ISSUE THREAD

**Issue by ypmacc** [nesteant/icpc-trainer#5]
When managing sub-encounter (reason/diagnosis/intervention) there should be options (radio button) either to add to the existing episode (drop-down with all the open episodes) or create new one  with the name (as per episode [naming rules](https://github.com/nesteant/icpc-trainer/issues/3))

**Comment by nesteant** [comment]
To be discussed. These fields are the part of the subvisit. There is no any consistency in allowing to do this.

**Comment by ypmacc** [comment]
Sub-encounters are grouped in the episodes of care, there's no inconsistency in the logic.

**Comment by nesteant** [comment]
Please provide mock of the view how this should look like

**Comment by ypmacc** [comment]
The controls are mentioned above. Here's the related requirement from the [spec](https://docs.google.com/document/d/1qaXZ4l4NqUfE2HEElig17agOxJU-vBvrG4fb8501MvQ/edit): "Можливість для лікаря присвоєння або зміни атрибуту «новий епізод МД», «продовження епізоду МД» або «завершення епізоду МД» для кожного візиту має бути доступною під час всієї сесії роботи з тренажером.
На одну дату програма повинна дозволяти створювати декілька звернень (підвізитів) із можливістю присвоєння атрибуту епізоду МД (п 4.1.) для кожного підвізиту."

**Comment by ypmacc** [comment]
https://marvelapp.com/2j6id9a

**Comment by nesteant** [comment]
So you want to change checkbox to radio group with controls disabled? 

Currently it is implemented like follows - https://prnt.sc/gzqgb2

**Comment by ypmacc** [comment]
Yes, I want this to be explicit: either creation of a new episode or appending to the existing one from the list of open episodes. Checkbox is a bit tricky.

**Comment by nesteant** [comment]
please check

**Comment by ypmacc** [comment]
Generally it looks ok, but there're some issues:
1. New episode - The diagnosis dropdown list part of the name doesn't work properly, the diagnoses aren't loaded.
2.  Existing episode - there should be a drop down with the open episodes, not text field.
