### ISSUE TITLE
Add close episode functionality

### ISSUE THREAD

**Issue by ypmacc** [nesteant/icpc-trainer#6]
There should be button to close the episode in the episode view/widget.

**Comment by ypmacc** [comment]
1) When selecting the data and entering non-date into text field, the modal dialog disappears.
2) There should be a possibility to view closed episodes (only open are visible by default)
3) Counter on the top should be refreshed after the episode is closed.

**Comment by nesteant** [comment]
All episodes are visible. Those which are closed are greyed out

**Comment by nesteant** [comment]
Counter shows how many episodes are displayed. Please specify requirements for this behavior.

e.g. as a icpc-triner user I want to see only opened episodes by default. I should have an options to view closed episodes if I press "show closed episodes button". Episodes counter should display amount of visible cards on the view

**Comment by nesteant** [comment]
Added validation to date field

**Comment by ypmacc** [comment]
1. The counter should show the amount of open episodes.
2. Separate "View closed episodes" button to the left of the "Новий візит"  button would be great. On the episode widget/popup there should be some mark stating that the episode is closed. Not sure how this should look like though, but the user should notice this. Any guess?
3. Validation works for me.

**Comment by nesteant** [comment]
Should counter show number of opened and closed episodes changing it value after you press the button?

**Comment by ypmacc** [comment]
It should show the number of open episodes. When doctor closes the episode the closed episode should disappear from the episodes list view and counter should be updated. The closed episode is now available in the closed episodes view (by clicking "view closed episodes" button as discussed above).

**Comment by ypmacc** [comment]
...I'm not sure about whether there should be an option to reopen the closed episode. We haven't discussed it earlier, but I just got the idea that this might occur in a real world. Will double check this.

**Comment by nesteant** [comment]
Please check

**Comment by ypmacc** [comment]
1. The counter works smoothly.
2. The button works for me. 
Please consider this one: "On the episode widget/popup there should be some mark stating that the episode is closed. Not sure how this should look like though, but the user should notice this. Any guess?"

**Comment by nesteant** [comment]
Added mark
