### ISSUE TITLE
Fix episode and sub-encounter view popups

### ISSUE THREAD

**Issue by ypmacc** [nesteant/icpc-trainer#7]
There're a couple of issues regarding episode view [popup](https://prnt.sc/gzpdzi)
1. ~~There should be an edit button, so we don't need to close the popup in order to edit the episode~~
2. ~~When clicking on sub-encounters of the episode [sub-encounter view](https://prnt.sc/gzph8m) title says "Деталі епізоду", while this is sub-encounter view, so it should say "Підвізит". Generally the sub-encounter view should look like the [following  ](https://marvelapp.com/3fi861f/screen/31221488).~~

**Comment by nesteant** [comment]
Add button in front of header inside details
Change name from Деталі to "Підвізит від <date>.\n<Episode name>"

**Comment by ypmacc** [comment]
* Sub-encounter view: there're no codes, [only the names](https://prnt.sc/h1ov5v).
