### ISSUE TITLE
Redesign Create subvisit

### ISSUE THREAD

**Issue by nesteant** [nesteant/icpc-trainer#8]
* ~~Add field boxes instead of tabs in order to show all information in the view~~
* ~~Each code should be collapsible and contain all additional information which is stored in the ICPC codes list~~
* ~~Each code can be modified by the HP. All information should be displayed~~
* ~~Episode should be pre-filled with the diagnosis selected on the previous step~~ 
* ~~Diagnosis dropdown should contain all diagnoses and should have search~~
* ~~Episode control (create subvisit, select existing episode) should show default options~~
* ~~Actions shouldn't be pre-filled from other tabs~~
* ~~Add episode - diagnosis should contain both code and description and be wider. Suffix can be shortened to 15-20 symbols~~

**Comment by ypmacc** [comment]
* ~~Episode widget (Patients->"Епізоди" tab): sub-encounters should be clickable just like on the episode popup. The sub-encounter popup view should be shown on clicking.~~
* ~~Encounters widget (Patients->"Візити" tab): sub-encounters should be clickable just like on the episode popup. The sub-encounter popup view should be shown on clicking.~~

**Comment by ypmacc** [comment]
>Each code should be collapsible and contain all additional information which is stored in the ICPC codes list

There're no codes, [only the names](https://prnt.sc/h13vls).

**Comment by ypmacc** [comment]
>Episode should be pre-filled with the diagnosis selected on the previous step

The diagnosis displayed in name field isn't the one that was [previously selected](https://prnt.sc/h13wlo).

**Comment by ypmacc** [comment]
> Diagnosis dropdown should contain all diagnoses and should have search

[No dropdown](https://prnt.sc/h13yj6) until the typing starts.

**Comment by ypmacc** [comment]
The rest seems to be ok.
